import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';

export function dataDirectory(
  platform = process.platform,
  home = os.homedir(),
  env: NodeJS.ProcessEnv = process.env,
): string {
  if (platform === 'win32')
    return path.join(
      env.LOCALAPPDATA && path.isAbsolute(env.LOCALAPPDATA)
        ? env.LOCALAPPDATA
        : path.join(home, 'AppData', 'Local'),
      'SubValue',
    );
  if (platform === 'darwin') return path.join(home, 'Library', 'Application Support', 'SubValue');
  return path.join(
    env.XDG_DATA_HOME && path.isAbsolute(env.XDG_DATA_HOME)
      ? env.XDG_DATA_HOME
      : path.join(home, '.local', 'share'),
    'subvalue',
  );
}

export function openBrowser(
  url: string,
  launch = spawn,
  platform = process.platform,
): Promise<boolean> {
  // URLs are generated by our loopback server; no shell interpolation is used.
  if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(url)) return Promise.resolve(false);
  const executable =
    platform === 'win32' ? 'rundll32' : platform === 'darwin' ? 'open' : 'xdg-open';
  const args = platform === 'win32' ? ['url.dll,FileProtocolHandler', url] : [url];
  return new Promise((resolve) => {
    const child = launch(executable, args, { stdio: 'ignore', windowsHide: true });
    let finished = false;
    const done = (ok: boolean) => {
      if (finished) return;
      finished = true;
      clearTimeout(timeout);
      resolve(ok);
    };
    const timeout = setTimeout(() => {
      child.unref();
      done(true);
    }, 3000);
    child.once('error', () => done(false));
    child.once('exit', (code) => done(code === 0));
  });
}
